; Exercise 14

;Draw the tree illustrating the process generated by the count-change procedure of section 1.2.2 in making change for 11 cents.
;What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?

(define (count-change amount)
  (cc amount 5))
(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1))
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins)))))
(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(count-change 11)

#|
(cc 11 5)
(+ (cc 11 4) (cc -50 5))
(+ (cc 11 3) (cc -25 5))
(+ (cc 11 2) (cc 1 5))
(+ (cc 11 1) (cc 6 5) (cc 1 5))
(+ (cc 11 0) (cc 10 5) (cc 6 5) (cc 1 5))
(+ (cc 10 5) (cc 6 5) (cc 1 5))
...
(+ (cc 10 2) (cc 0 5) (cc 6 5) (cc 1 5))
(+ 1 (cc 6 5) (cc 1 5))
(+ 1 (cc 6 1) (cc 1 5) (cc 1 5))
(+ 1 (cc 6 0) (cc 5 5) (cc 1 5) (cc 1 5))
(+ 1 (cc 5 5) (cc 1 5) (cc 1 5))
...
(+ 1 (cc 5 1) (cc 0 5) (cc 1 5) (cc 1 5))
(+ 1 1 (cc 1 5) (cc 1 5))
...
(+ 1 1 (cc 1 0) (cc 0 1) (cc 1 0) (cc 0 1))
(+ 1 1 1 1)
== 4

Not a tree, because I'm too fucking lazy to draw it out like that
This will suffice.
|#